/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Briana Margetts
 * Created: 10/05/2021
 */

CREATE TABLE "USER"(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100000, INCREMENT BY 1),
    EMAIL VARCHAR(255) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    GENDER VARCHAR(255) NOT NULL,
    DOB VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE "ADMIN" (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100, INCREMENT BY 1),
    EMAIL VARCHAR(255) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    DOB VARCHAR(255) NOT NULL,
    "ROLE" VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID) 
);

CREATE TABLE CUSTOMER (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100, INCREMENT BY 1),
    EMAIL VARCHAR(255) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    DOB VARCHAR(255) NOT NULL,
    "ROLE" VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE "ORDER"(
    ORDERID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100, INCREMENT BY 1),
    CUSTOMERID INTEGER,
    PAYMENTID INTEGER NOT NULL,
    DEVICEID INTEGER NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    INVOICEID INTEGER NOT NULL,
    "DATE" VARCHAR(255) NOT NULL,
    PRIMARY KEY(ORDERID)
);

CREATE TABLE DEVICE(
    DEVICEID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100, INCREMENT BY 1),
    "NAME" VARCHAR(20) NOT NULL,
    MANUFACTURER VARCHAR(20),
    ORIGIN VARCHAR(20),
    "TYPE" VARCHAR(20),
    INSTOCK BOOLEAN, /* when inserting values 1 = instock and 0 = not instock*/
    PRICEPERUNIT DOUBLE NOT NULL,
    STOCK_NUM INTEGER NOT NULL,
    PRIMARY KEY(DEVICEID)
);

CREATE TABLE "INVOICE"(
    INVOICEID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100, INCREMENT BY 1),
    RECIPIENTEMAIL VARCHAR(255) NOT NULL,
    CONTENT VARCHAR(255) NOT NULL,
    PRIMARY KEY(INVOICEID)
);


CREATE TABLE ORDERLINEITEM(
    DEVICEID INTEGER NOT NULL,
    ORDERID INTEGER NOT NULL,
    "COUNT" INTEGER,
    FOREIGN KEY(DEVICEID) REFERENCES DEVICE(DEVICEID),
    FOREIGN KEY(ORDERID) REFERENCES "ORDER"(ORDERID)
);


CREATE TABLE PAYMENT(
    PAYMENTID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100, INCREMENT BY 1),
    METHODID INTEGER NOT NULL,
    AMMOUNT DOUBLE NOT NULL,
    PAYMENTDATE VARCHAR(255),
    PRIMARY KEY(PAYMENTID)
);

CREATE TABLE SHIPMENT (
    SHIPMENT_ID INTEGER(10) NOT NULL,
    PAYMENT_ID INTEGER(10)  NOT NULL,
    SHIPPING_DATE VARCHAR(10) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    SHIPPING_ADDRESS VARCHAR(100) NOT NULL,
    PRIMARY KEY(SHIPMENT_ID) 
);

CREATE TABLE STAFF (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100, INCREMENT BY 1),
    EMAIL VARCHAR(255) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    DOB VARCHAR(255) NOT NULL,
    "ROLE" VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE PAYMENTMETHOD(
    METHODID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 100, INCREMENT BY 1),
    CUSTOMERID INTEGER NOT NULL,
    PAYMENTTYPE VARCHAR(255) NOT NULL,
    ACCOUNTNUMBER VARCHAR(255) NOT NULL,
    CCV INTEGER NOT NULL,
    PRIMARY KEY(MEHTODID)
);